name: test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Install pre-commit
      uses: BSFishy/pip-action@v1
      with:
        packages: pre-commit

    - name: valid-gitlab-ci.yml should validate
      run: pre-commit try-repo https://github.com/FalcoSuessgott/pre-commit-gitlab-ci gitlab-ci --ref ${GITHUB_REF##*/} --files testdata/valid-gitlab-ci.yml
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}

    - name: invalid-gitlab-ci.yml should fail
      id: failing_test
      run: |
        pre-commit try-repo https://github.com/FalcoSuessgott/pre-commit-gitlab-ci gitlab-ci --ref ${GITHUB_REF##*/} --files testdata/invalid-gitlab-ci.yml || true
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}



